-- Remove Gujarati wording from seeded item names (bulk finished goods).
UPDATE `Item` SET `name` = 'Groundnut Oil (Peanut Oil)' WHERE `name` = 'Groundnut Oil (Peanut Oil) – સીંગતેલ';
UPDATE `Item` SET `name` = 'Mustard Oil' WHERE `name` = 'Mustard Oil – રાયનું તેલ';
UPDATE `Item` SET `name` = 'Castor Oil' WHERE `name` = 'Castor Oil – દિવેલ';
UPDATE `Item` SET `name` = 'Sesame Oil (Til Oil)' WHERE `name` = 'Sesame Oil (Til Oil) – તલ તેલ';
UPDATE `Item` SET `name` = 'Black Sesame Oil' WHERE `name` = 'Black Sesame Oil – કાળાતલનું તેલ';
UPDATE `Item` SET `name` = 'Sunflower Oil' WHERE `name` = 'Sunflower Oil – સુર્યમુખીનું તેલ';
UPDATE `Item` SET `name` = 'Coconut Oil' WHERE `name` = 'Coconut Oil – કોપરેલ';
UPDATE `Item` SET `name` = 'Almond Oil' WHERE `name` = 'Almond Oil – બદામ તેલ';

-- Remove Gujarati wording from seeded item names (packaged finished goods).
UPDATE `Item` SET `name` = 'Groundnut Oil (Peanut Oil) - 500ml' WHERE `name` = 'Groundnut Oil (Peanut Oil) (સીંગતેલ) - 500ml';
UPDATE `Item` SET `name` = 'Groundnut Oil (Peanut Oil) - 1Ltr' WHERE `name` = 'Groundnut Oil (Peanut Oil) (સીંગતેલ) - 1Ltr';
UPDATE `Item` SET `name` = 'Groundnut Oil (Peanut Oil) - 5Ltr' WHERE `name` = 'Groundnut Oil (Peanut Oil) (સીંગતેલ) - 5Ltr';
UPDATE `Item` SET `name` = 'Groundnut Oil (Peanut Oil) - 15Ltr' WHERE `name` = 'Groundnut Oil (Peanut Oil) (સીંગતેલ) - 15Ltr';
UPDATE `Item` SET `name` = 'Mustard Oil - 200ml' WHERE `name` = 'Mustard Oil (રાયણું તેલ) - 200ml';
UPDATE `Item` SET `name` = 'Mustard Oil - 500ml' WHERE `name` = 'Mustard Oil (રાયણું તેલ) - 500ml';
UPDATE `Item` SET `name` = 'Mustard Oil - 1Ltr' WHERE `name` = 'Mustard Oil (રાયણું તેલ) - 1Ltr';
UPDATE `Item` SET `name` = 'Mustard Oil - 5Ltr' WHERE `name` = 'Mustard Oil (રાયણું તેલ) - 5Ltr';
UPDATE `Item` SET `name` = 'Mustard Oil - 15Ltr' WHERE `name` = 'Mustard Oil (રાયણું તેલ) - 15Ltr';
UPDATE `Item` SET `name` = 'Castor Oil - 200ml' WHERE `name` = 'Castor Oil (દિવેલ) - 200ml';
UPDATE `Item` SET `name` = 'Castor Oil - 500ml' WHERE `name` = 'Castor Oil (દિવેલ) - 500ml';
UPDATE `Item` SET `name` = 'Castor Oil - 1Ltr' WHERE `name` = 'Castor Oil (દિવેલ) - 1Ltr';
UPDATE `Item` SET `name` = 'Castor Oil - 5Ltr' WHERE `name` = 'Castor Oil (દિવેલ) - 5Ltr';
UPDATE `Item` SET `name` = 'Castor Oil - 15Ltr' WHERE `name` = 'Castor Oil (દિવેલ) - 15Ltr';
UPDATE `Item` SET `name` = 'Sesame Oil (Til Oil) - 200ml' WHERE `name` = 'Sesame Oil (Til Oil) (તલ તેલ) - 200ml';
UPDATE `Item` SET `name` = 'Sesame Oil (Til Oil) - 500ml' WHERE `name` = 'Sesame Oil (Til Oil) (તલ તેલ) - 500ml';
UPDATE `Item` SET `name` = 'Sesame Oil (Til Oil) - 1Ltr' WHERE `name` = 'Sesame Oil (Til Oil) (તલ તેલ) - 1Ltr';
UPDATE `Item` SET `name` = 'Sesame Oil (Til Oil) - 5Ltr' WHERE `name` = 'Sesame Oil (Til Oil) (તલ તેલ) - 5Ltr';
UPDATE `Item` SET `name` = 'Sesame Oil (Til Oil) - 15Ltr' WHERE `name` = 'Sesame Oil (Til Oil) (તલ તેલ) - 15Ltr';
UPDATE `Item` SET `name` = 'Black Sesame Oil - 200ml' WHERE `name` = 'Black Sesame Oil (કાળાતલનું તેલ) - 200ml';
UPDATE `Item` SET `name` = 'Black Sesame Oil - 500ml' WHERE `name` = 'Black Sesame Oil (કાળાતલનું તેલ) - 500ml';
UPDATE `Item` SET `name` = 'Black Sesame Oil - 1Ltr' WHERE `name` = 'Black Sesame Oil (કાળાતલનું તેલ) - 1Ltr';
UPDATE `Item` SET `name` = 'Black Sesame Oil - 5Ltr' WHERE `name` = 'Black Sesame Oil (કાળાતલનું તેલ) - 5Ltr';
UPDATE `Item` SET `name` = 'Black Sesame Oil - 15Ltr' WHERE `name` = 'Black Sesame Oil (કાળાતલનું તેલ) - 15Ltr';
UPDATE `Item` SET `name` = 'Sunflower Oil - 200ml' WHERE `name` = 'Sunflower Oil (સૂર્યમુખીનું તેલ) - 200ml';
UPDATE `Item` SET `name` = 'Sunflower Oil - 500ml' WHERE `name` = 'Sunflower Oil (સૂર્યમુખીનું તેલ) - 500ml';
UPDATE `Item` SET `name` = 'Sunflower Oil - 1Ltr' WHERE `name` = 'Sunflower Oil (સૂર્યમુખીનું તેલ) - 1Ltr';
UPDATE `Item` SET `name` = 'Sunflower Oil - 5Ltr' WHERE `name` = 'Sunflower Oil (સૂર્યમુખીનું તેલ) - 5Ltr';
UPDATE `Item` SET `name` = 'Sunflower Oil - 15Ltr' WHERE `name` = 'Sunflower Oil (સૂર્યમુખીનું તેલ) - 15Ltr';
UPDATE `Item` SET `name` = 'Coconut Oil - 100ml' WHERE `name` = 'Coconut Oil (કોપરેલ) - 100ml';
UPDATE `Item` SET `name` = 'Coconut Oil - 200ml' WHERE `name` = 'Coconut Oil (કોપરેલ) - 200ml';
UPDATE `Item` SET `name` = 'Coconut Oil - 500ml' WHERE `name` = 'Coconut Oil (કોપરેલ) - 500ml';
UPDATE `Item` SET `name` = 'Coconut Oil - 1Ltr' WHERE `name` = 'Coconut Oil (કોપરેલ) - 1Ltr';
UPDATE `Item` SET `name` = 'Coconut Oil - 5Ltr' WHERE `name` = 'Coconut Oil (કોપરેલ) - 5Ltr';
UPDATE `Item` SET `name` = 'Coconut Oil - 15Ltr' WHERE `name` = 'Coconut Oil (કોપરેલ) - 15Ltr';
UPDATE `Item` SET `name` = 'Almond Oil - 50ml' WHERE `name` = 'Almond Oil (બદામ તેલ) - 50ml';
UPDATE `Item` SET `name` = 'Almond Oil - 100ml' WHERE `name` = 'Almond Oil (બદામ તેલ) - 100ml';
UPDATE `Item` SET `name` = 'Almond Oil - 200ml' WHERE `name` = 'Almond Oil (બદામ તેલ) - 200ml';
UPDATE `Item` SET `name` = 'Almond Oil - 500ml' WHERE `name` = 'Almond Oil (બદામ તેલ) - 500ml';
